<a href="https://colab.research.google.com/github/Noob919/Feature_selection/blob/main/OWA/Votin84_OWA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
import numpy as np
import pandas as pd
from functools import reduce
from itertools import permutations

In [85]:
rank1 = pd.read_excel("/content/voting84_dataset.xlsx",sheet_name = "Chi_2").set_index('Attributes_Names')
rank2  = pd.read_excel("/content/voting84_dataset.xlsx",sheet_name = "Tree_based_method").set_index('Attributes_Names')
rank3  = pd.read_excel("/content/voting84_dataset.xlsx",sheet_name = "permutation_method_mean").set_index('Attributes_Names')
rank5  = pd.read_excel("/content/voting84_dataset.xlsx",sheet_name = "PCA").set_index('Attributes_Names')
rank4  = pd.read_excel("/content/voting84_dataset.xlsx",sheet_name = "permutation_method_std").set_index('Attributes_Names')
rank6  = pd.read_excel("/content/voting84_dataset.xlsx",sheet_name = "F_test").set_index('Attributes_Names')
rank7  = pd.read_excel("/content/voting84_dataset.xlsx",sheet_name = "mutual_info").set_index('Attributes_Names')
rank8  = pd.read_excel("/content/voting84_dataset.xlsx",sheet_name = "Pearson_Correlation").set_index('Attributes_Names')

In [86]:
ranks = [rank1,rank2,rank3,rank4,rank5,rank6,rank7,rank8]
final_df = reduce(lambda  left,right: pd.merge(left,right,on=['Attributes_Names'],how='inner'), ranks)
final_df.shape

(16, 8)

In [87]:
negative_df = final_df*-1
negative_df

,rank_chi,rank_tree,rank_per_mean,rank_P_std,rank_pca,rank_f_test,Mutual_info_rank,rank_pearson
Attributes_Names,,,,,,,,
physician-fee-freeze,-1,-1,-1,-1,-2,-1,-1,-1
education-spending,-2,-3,-16,-12,-3,-3,-3,-3
el-salvador-aid,-3,-4,-15,-10,-1,-4,-4,-2
adoption-of-the-budget-resolution,-4,-2,-3,-2,-14,-2,-2,-16
mx-missile,-5,-6,-7,-4,-15,-6,-6,-15
duty-free-exports,-6,-9,-6,-5,-12,-9,-9,-13
aid-to-nicaraguan-contras,-7,-7,-12,-16,-16,-5,-7,-14
crime,-8,-8,-14,-9,-4,-7,-5,-4
superfund-right-to-sue,-9,-10,-11,-15,-5,-8,-8,-5
anti-satellite-test-ban,-10,-11,-5,-8,-13,-10,-11,-12
synfuels-corporation-cutback,-11,-5,-2,-3,-9,-13,-10,-10
handicapped-infants,-12,-13,-13,-11,-11,-12,-12,-11
religious-groups-in-schools,-13,-15,-8,-7,-6,-11,-13,-6
export-administration-act-south-africa,-14,-16,-10,-14,-10,-14,-14,-9
immigration,-15,-12,-4,-6,-8,-15,-16,-7
water-project-cost-sharing,-16,-14,-9,-13,-7,-16,-15,-8

In [88]:
perms = list(permutations(final_df.index,2)) 
perm_df = pd.DataFrame(perms, columns = ['feature A', 'feature B'])
perm_df

                       feature A                                feature B
0           physician-fee-freeze                       education-spending
1           physician-fee-freeze                          el-salvador-aid
2           physician-fee-freeze        adoption-of-the-budget-resolution
3           physician-fee-freeze                               mx-missile
4           physician-fee-freeze                        duty-free-exports
..                           ...                                      ...
235   water-project-cost-sharing             synfuels-corporation-cutback
236   water-project-cost-sharing                      handicapped-infants
237   water-project-cost-sharing              religious-groups-in-schools
238   water-project-cost-sharing   export-administration-act-south-africa
239   water-project-cost-sharing                              immigration

[240 rows x 2 columns]

In [89]:
rank_chi = []
for i in range(0,perm_df.shape[0]):
  if(negative_df.T[perm_df['feature A'][i]]['rank_chi'] > negative_df.T[perm_df['feature B'][i]]['rank_chi']):
    rank_chi.append(1)
  else: 
    rank_chi.append(0)

perm_df = perm_df.merge(pd.Series(rank_chi, name = 'Chi2').to_frame(), left_index=True, right_index=True)

In [90]:
rank_tree = []
for i in range(0,perm_df.shape[0]):
  if(negative_df.T[perm_df['feature A'][i]]['rank_tree'] > negative_df.T[perm_df['feature B'][i]]['rank_tree']):
    rank_tree.append(1)
  else: 
    rank_tree.append(0)

perm_df = perm_df.merge(pd.Series(rank_tree, name = 'tree').to_frame(), left_index=True, right_index=True)

In [91]:
rank_per_mean = []
for i in range(0,perm_df.shape[0]):
  if(negative_df.T[perm_df['feature A'][i]]['rank_per_mean'] > negative_df.T[perm_df['feature B'][i]]['rank_per_mean']):
    rank_per_mean.append(1)
  else: 
    rank_per_mean.append(0)

perm_df = perm_df.merge(pd.Series(rank_per_mean, name = 'per_mean').to_frame(), left_index=True, right_index=True)

In [92]:
rank_P_std = []
for i in range(0,perm_df.shape[0]):
  if(negative_df.T[perm_df['feature A'][i]]['rank_P_std'] > negative_df.T[perm_df['feature B'][i]]['rank_P_std']):
    rank_P_std.append(1)
  else: 
    rank_P_std.append(0)

perm_df = perm_df.merge(pd.Series(rank_P_std, name = 'per_std').to_frame(), left_index=True, right_index=True)

In [93]:
rank_pca = []
for i in range(0,perm_df.shape[0]):
  if(negative_df.T[perm_df['feature A'][i]]['rank_pca'] > negative_df.T[perm_df['feature B'][i]]['rank_pca']):
    rank_pca.append(1)
  else: 
    rank_pca.append(0)

perm_df = perm_df.merge(pd.Series(rank_pca, name = 'rank_pca').to_frame(), left_index=True, right_index=True)

In [94]:
rank_f_test = []
for i in range(0,perm_df.shape[0]):
  if(negative_df.T[perm_df['feature A'][i]]['rank_f_test'] > negative_df.T[perm_df['feature B'][i]]['rank_f_test']):
    rank_f_test.append(1)
  else: 
    rank_f_test.append(0)

perm_df = perm_df.merge(pd.Series(rank_f_test, name = 'rank_f_test').to_frame(), left_index=True, right_index=True)

In [95]:
rank_mutual_info = []
for i in range(0,perm_df.shape[0]):
  if(negative_df.T[perm_df['feature A'][i]][ 'Mutual_info_rank'] > negative_df.T[perm_df['feature B'][i]]['Mutual_info_rank']):
    rank_mutual_info.append(1)
  else: 
    rank_mutual_info.append(0)

perm_df = perm_df.merge(pd.Series(rank_mutual_info, name = 'rank_mutual').to_frame(), left_index=True, right_index=True)

In [96]:
rank_pearson = []
for i in range(0,perm_df.shape[0]):
  if(negative_df.T[perm_df['feature A'][i]]['rank_pearson'] > negative_df.T[perm_df['feature B'][i]]['rank_pearson']):
    rank_pearson.append(1)
  else: 
    rank_pearson.append(0)

perm_df = perm_df.merge(pd.Series(rank_pearson, name = 'rank_pearson').to_frame(), left_index=True, right_index=True)

In [97]:
perm_df[:60]

,feature A,feature B,Chi2,tree,per_mean,per_std,rank_pca,rank_f_test,rank_mutual,rank_pearson
0,physician-fee-freeze,education-spending,1,1,1,1,1,1,1,1
1,physician-fee-freeze,el-salvador-aid,1,1,1,1,0,1,1,1
2,physician-fee-freeze,adoption-of-the-budget-resolution,1,1,1,1,1,1,1,1
3,physician-fee-freeze,mx-missile,1,1,1,1,1,1,1,1
4,physician-fee-freeze,duty-free-exports,1,1,1,1,1,1,1,1
5,physician-fee-freeze,aid-to-nicaraguan-contras,1,1,1,1,1,1,1,1
6,physician-fee-freeze,crime,1,1,1,1,1,1,1,1
7,physician-fee-freeze,superfund-right-to-sue,1,1,1,1,1,1,1,1
8,physician-fee-freeze,anti-satellite-test-ban,1,1,1,1,1,1,1,1
9,physician-fee-freeze,synfuels-corporation-cutback,1,1,1,1,1,1,1,1
10,physician-fee-freeze,handicapped-infants,1,1,1,1,1,1,1,1
11,physician-fee-freeze,religious-groups-in-schools,1,1,1,1,1,1,1,1
12,physician-fee-freeze,export-administration-act-south-africa,1,1,1,1,1,1,1,1
13,physician-fee-freeze,immigration,1,1,1,1,1,1,1,1
14,physician-fee-freeze,water-project-cost-sharing,1,1,1,1,1,1,1,1
15,education-spending,physician-fee-freeze,0,0,0,0,0,0,0,0
16,education-spending,el-salvador-aid,1,1,0,0,0,1,1,0
17,education-spending,adoption-of-the-budget-resolution,1,0,0,0,1,0,0,1
18,education-spending,mx-missile,1,1,0,0,1,1,1,1
19,education-spending,duty-free-exports,1,1,0,0,1,1,1,1
20,education-spending,aid-to-nicaraguan-contras,1,1,0,1,1,1,1,1
21,education-spending,crime,1,1,0,0,1,1,1,1
22,education-spending,superfund-right-to-sue,1,1,0,1,1,1,1,1
23,education-spending,anti-satellite-test-ban,1,1,0,0,1,1,1,1
24,education-spending,synfuels-corporation-cutback,1,1,0,0,1,1,1,1
25,education-spending,handicapped-infants,1,1,0,0,1,1,1,1
26,education-spending,religious-groups-in-schools,1,1,0,0,1,1,1,1
27,education-spending,export-administration-act-south-africa,1,1,0,1,1,1,1,1
28,education-spending,immigration,1,1,0,0,1,1,1,1
29,education-spending,water-project-cost-sharing,1,1,0,1,1,1,1,1
30,el-salvador-aid,physician-fee-freeze,0,0,0,0,1,0,0,0
31,el-salvador-aid,education-spending,0,0,1,1,1,0,0,1
32,el-salvador-aid,adoption-of-the-budget-resolution,1,0,0,0,1,0,0,1
33,el-salvador-aid,mx-missile,1,1,0,0,1,1,1,1
34,el-salvador-aid,duty-free-exports,1,1,0,0,1,1,1,1
35,el-salvador-aid,aid-to-nicaraguan-contras,1,1,0,1,1,1,1,1
36,el-salvador-aid,crime,1,1,0,0,1,1,1,1
37,el-salvador-aid,superfund-right-to-sue,1,1,0,1,1,1,1,1
38,el-salvador-aid,anti-satellite-test-ban,1,1,0,0,1,1,1,1
39,el-salvador-aid,synfuels-corporation-cutback,1,1,0,0,1,1,1,1
40,el-salvador-aid,handicapped-infants,1,1,0,1,1,1,1,1
41,el-salvador-aid,religious-groups-in-schools,1,1,0,0,1,1,1,1
42,el-salvador-aid,export-administration-act-south-africa,1,1,0,1,1,1,1,1
43,el-salvador-aid,immigration,1,1,0,0,1,1,1,1
44,el-salvador-aid,water-project-cost-sharing,1,1,0,1,1,1,1,1
45,adoption-of-the-budget-resolution,physician-fee-freeze,0,0,0,0,0,0,0,0
46,adoption-of-the-budget-resolution,education-spending,0,1,1,1,0,1,1,0
47,adoption-of-the-budget-resolution,el-salvador-aid,0,1,1,1,0,1,1,0
48,adoption-of-the-budget-resolution,mx-missile,1,1,1,1,1,1,1,0
49,adoption-of-the-budget-resolution,duty-free-exports,1,1,1,1,0,1,1,0
50,adoption-of-the-budget-resolution,aid-to-nicaraguan-contras,1,1,1,1,1,1,1,0
51,adoption-of-the-budget-resolution,crime,1,1,1,1,0,1,1,0
52,adoption-of-the-budget-resolution,superfund-right-to-sue,1,1,1,1,0,1,1,0
53,adoption-of-the-budget-resolution,anti-satellite-test-ban,1,1,1,1,0,1,1,0
54,adoption-of-the-budget-resolution,synfuels-corporation-cutback,1,1,0,1,0,1,1,0
55,adoption-of-the-budget-resolution,handicapped-infants,1,1,1,1,0,1,1,0
56,adoption-of-the-budget-resolution,religious-groups-in-schools,1,1,1,1,0,1,1,0
57,adoption-of-the-budget-resolution,export-administration-act-south-africa,1,1,1,1,0,1,1,0
58,adoption-of-the-budget-resolution,immigration,1,1,1,1,0,1,1,0
59,adoption-of-the-budget-resolution,water-project-cost-sharing,1,1,1,1,0,1,1,0

In [98]:
Name = pd.DataFrame(list(negative_df.index),columns = ['Attributes_Name'])
Name

                            Attributes_Name
0                      physician-fee-freeze
1                        education-spending
2                           el-salvador-aid
3         adoption-of-the-budget-resolution
4                                mx-missile
5                         duty-free-exports
6                 aid-to-nicaraguan-contras
7                                     crime
8                    superfund-right-to-sue
9                   anti-satellite-test-ban
10             synfuels-corporation-cutback
11                      handicapped-infants
12              religious-groups-in-schools
13   export-administration-act-south-africa
14                              immigration
15               water-project-cost-sharing

In [99]:
PS_Chi = []
for i in negative_df.index:
    PS_Chi.append((((perm_df[perm_df['feature A'] == i]['Chi2'].sum())/15)))
    
Name = Name.merge(pd.Series(PS_Chi, name = 'PS_Chi').to_frame(), left_index=True, right_index=True)
Name

                            Attributes_Name    PS_Chi
0                      physician-fee-freeze  1.000000
1                        education-spending  0.933333
2                           el-salvador-aid  0.866667
3         adoption-of-the-budget-resolution  0.800000
4                                mx-missile  0.733333
5                         duty-free-exports  0.666667
6                 aid-to-nicaraguan-contras  0.600000
7                                     crime  0.533333
8                    superfund-right-to-sue  0.466667
9                   anti-satellite-test-ban  0.400000
10             synfuels-corporation-cutback  0.333333
11                      handicapped-infants  0.266667
12              religious-groups-in-schools  0.200000
13   export-administration-act-south-africa  0.133333
14                              immigration  0.066667
15               water-project-cost-sharing  0.000000

In [100]:
PS_Tree = []
for i in negative_df.index:
    PS_Tree.append((((perm_df[perm_df['feature A'] == i]['tree'].sum())/15)))
    
Name = Name.merge(pd.Series(PS_Tree, name = 'PS_Tree').to_frame(), left_index=True, right_index=True)

In [101]:
PS_per_mean = []
for i in negative_df.index:
    PS_per_mean.append((((perm_df[perm_df['feature A'] == i]['per_mean'].sum())/15)))
    
Name = Name.merge(pd.Series(PS_per_mean, name = 'PS_per_mean').to_frame(), left_index=True, right_index=True)

In [102]:
PS_per_std = []
for i in negative_df.index:
    PS_per_std.append((((perm_df[perm_df['feature A'] == i]['per_std'].sum())/15)))
    
Name = Name.merge(pd.Series(PS_per_std, name = 'PS_per_std').to_frame(), left_index=True, right_index=True)

In [103]:
PS_pca = []
for i in negative_df.index:
    PS_pca.append((((perm_df[perm_df['feature A'] == i]['rank_pca'].sum())/15)))
    
Name = Name.merge(pd.Series(PS_pca, name = 'PS_pca').to_frame(), left_index=True, right_index=True)

In [104]:
PS_f_test = []
for i in negative_df.index:
    PS_f_test.append((((perm_df[perm_df['feature A'] == i]['rank_f_test'].sum())/15)))
    
Name = Name.merge(pd.Series(PS_f_test, name = 'PS_f_test').to_frame(), left_index=True, right_index=True)

In [105]:
PS_mutual = []
for i in negative_df.index:
    PS_mutual.append((((perm_df[perm_df['feature A'] == i]['rank_mutual'].sum())/15)))
    
Name = Name.merge(pd.Series(PS_mutual, name = 'PS_mutual').to_frame(), left_index=True, right_index=True)

In [106]:
PS_pearson = []
for i in negative_df.index:
    PS_pearson.append((((perm_df[perm_df['feature A'] == i]['rank_pearson'].sum())/15)))
    
Name = Name.merge(pd.Series(PS_pearson, name = 'PS_pearson').to_frame(), left_index=True, right_index=True)

In [107]:
PS = Name.set_index('Attributes_Name')
PS

,PS_Chi,PS_Tree,PS_per_mean,PS_per_std,PS_pca,PS_f_test,PS_mutual,PS_pearson
Attributes_Name,,,,,,,,
physician-fee-freeze,1.000000,1.000000,1.000000,1.000000,0.933333,1.000000,1.000000,1.000000
education-spending,0.933333,0.866667,0.000000,0.266667,0.866667,0.866667,0.866667,0.866667
el-salvador-aid,0.866667,0.800000,0.066667,0.400000,1.000000,0.800000,0.800000,0.933333
adoption-of-the-budget-resolution,0.800000,0.933333,0.866667,0.933333,0.133333,0.933333,0.933333,0.000000
mx-missile,0.733333,0.666667,0.600000,0.800000,0.066667,0.666667,0.666667,0.066667
duty-free-exports,0.666667,0.466667,0.666667,0.733333,0.266667,0.466667,0.466667,0.200000
aid-to-nicaraguan-contras,0.600000,0.600000,0.266667,0.000000,0.000000,0.733333,0.600000,0.133333
crime,0.533333,0.533333,0.133333,0.466667,0.800000,0.600000,0.733333,0.800000
superfund-right-to-sue,0.466667,0.400000,0.333333,0.066667,0.733333,0.533333,0.533333,0.733333
anti-satellite-test-ban,0.400000,0.333333,0.733333,0.533333,0.200000,0.400000,0.333333,0.266667
synfuels-corporation-cutback,0.333333,0.733333,0.933333,0.866667,0.466667,0.200000,0.400000,0.400000
handicapped-infants,0.266667,0.200000,0.200000,0.333333,0.333333,0.266667,0.266667,0.333333
religious-groups-in-schools,0.200000,0.066667,0.533333,0.600000,0.666667,0.333333,0.200000,0.666667
export-administration-act-south-africa,0.133333,0.000000,0.400000,0.133333,0.400000,0.133333,0.133333,0.466667
immigration,0.066667,0.266667,0.800000,0.666667,0.533333,0.066667,0.000000,0.600000
water-project-cost-sharing,0.000000,0.133333,0.466667,0.200000,0.600000,0.000000,0.066667,0.533333

In [108]:
def Q(r):
  a = 0.3
  b = 0.8
  if(r < a):
    q = 0
  
  elif(a <= r <= 0.8):
    q =(r-0.3)/(b-a)
    
  elif(r>0.8):
    q =1
    
  return q

In [109]:
w_chi = Q(1/8) - Q(0)
w_tree = Q(2/8) - Q(1/8)
w_per_mean = Q(3/8) - Q(2/8)
w_per_std = Q(4/8) - Q(3/8)
w_pca = Q(5/8) - Q(4/8)
w_f_test = Q(6/8) -Q(5/8)
w_mutual = Q(7/8) - Q(6/8)
w_pearson = Q(8/8) - Q(7/8)
w  = [w_chi,w_tree,w_per_mean,w_per_std,w_pca,w_f_test,w_mutual,w_pearson]

In [110]:
FS = []
for i in range(0,len(Name.index)):
  sum = 0 
  fs = PS.iloc[i].sort_values(ascending = False)
  for j in range(0,len(fs)):
    sum  = sum + fs[j]*w[j]
  FS.append(sum) 
FS

[1.0,
 0.8066666666666666,
 0.77,
 0.8033333333333333,
 0.5900000000000001,
 0.47666666666666674,
 0.33999999999999997,
 0.5733333333333333,
 0.4633333333333334,
 0.35333333333333333,
 0.45999999999999996,
 0.27,
 0.37666666666666665,
 0.17333333333333334,
 0.3133333333333333,
 0.17]

In [111]:
Final_df  = Name.merge(pd.Series(FS, name = 'FinalScore').to_frame(), left_index=True, right_index=True)
Final_df  =  Final_df[['Attributes_Name','FinalScore']].sort_values(by = 'FinalScore', ascending = False)
Final_df

                            Attributes_Name  FinalScore
0                      physician-fee-freeze    1.000000
1                        education-spending    0.806667
3         adoption-of-the-budget-resolution    0.803333
2                           el-salvador-aid    0.770000
4                                mx-missile    0.590000
7                                     crime    0.573333
5                         duty-free-exports    0.476667
8                    superfund-right-to-sue    0.463333
10             synfuels-corporation-cutback    0.460000
12              religious-groups-in-schools    0.376667
9                   anti-satellite-test-ban    0.353333
6                 aid-to-nicaraguan-contras    0.340000
14                              immigration    0.313333
11                      handicapped-infants    0.270000
13   export-administration-act-south-africa    0.173333
15               water-project-cost-sharing    0.170000

In [112]:
from openpyxl import load_workbook

book = load_workbook('/content/voting84_dataset.xlsx')
writer = pd.ExcelWriter('/content/voting84_dataset.xlsx', engine='openpyxl') 
writer.book = book

## ExcelWriter for some reason uses writer.sheets to access the sheet.
## If you leave it empty it will not know that sheet Main is already there
## and will create a new sheet.

writer.sheets = dict((ws.title, ws) for ws in book.worksheets)

Final_df.to_excel(writer, "OWA_method")

writer.save()